lzc-sdk-version: "0.1"
name: MoonTV
package: cloud.lazycat.app.moontv
version: 0.0.1
description: 开箱即用的、跨平台的影视聚合播放器
homepage: https://github.com/senshinya/MoonTV
author: senshinya
application:
    subdomain: moontv
    background_task: false
    multi_instance: false
    public_path:
        - /
    routes:
        - /=http://moontv:3000/
services:
    moontv:
        image: registry.lazycat.cloud/czyt/senshinya/moontv:0d5920d59c794278
