name: MoonTV
package: lazycat.coummunity.app.moontv
version: 2.3.0
min_os_version: 1.3.8
description: 开箱即用的、跨平台的影视聚合播放器
homepage: https://github.com/MoonTechLab/LunaTV
author: MoonTechLab
application:
    subdomain: moontv

    public_path:
        - /
    upstreams:
        - location: /
          backend: http://moontv:3000

services:
    moontv:
        # ghcr.io/moontechlab/lunatv:2.3.0
        image: registry.lazycat.cloud/czyt/moontechlab/lunatv:020ef094507083ff
        environment:
            - USERNAME={{ .U.admin_username }}
            - PASSWORD={{.U.admin_password}}
            - NEXT_PUBLIC_ENABLE_REGISTER={{.U.enable_register}}
            - NEXT_PUBLIC_STORAGE_TYPE=redis
            - REDIS_URL=redis://moontv-redis:6379
        depends_on:
            - moontv-redis

    moontv-redis:
        image: registry.lazycat.cloud/edward/library/redis:4c6b9d7b7a334a2e
        binds:
            - /lzcapp/var/redis:/data
